#자동차 정보 테이블 생성
CREATE TABLE CAR_INFO(
	CAR_NUM INT PRIMARY KEY AUTO_INCREMENT
	,MODEL_NUM INT NOT NULL
	,MODEL_NAME VARCHAR(20) NOT NULL
	,PRICE INT NOT NULL
	,COMPANY VARCHAR(20) NOT NULL
);

SELECT * FROM CAR_INFO;

SELECT CAR_NUM
	,MODEL_NUM
	,MODEL_NAME
	,COMPANY
FROM CAR_INFO
ORDER BY CAR_NUM DESC;

DELETE  FROM CAR_INFO;
