#자동차 정보 테이블 생성
CREATE TABLE CAR_INFO(
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT
	,MODEL_NAME VARCHAR(20) NOT NULL
	,PRICE INT NOT NULL
	,COMPANY VARCHAR(20) NOT NULL
);

SELECT * FROM CAR_INFO;

#판매 정보 등록 테이블 생성

DROP TABLE IF EXISTS SALE_INFO;

CREATE TABLE SALE_INFO(
	SALE_NUM INT PRIMARY KEY AUTO_INCREMENT
	,BUYER VARCHAR(10) NOT NULL
	,COLOR VARCHAR(20) NOT NULL
	,PHONE VARCHAR(13)
	,BUY_DATE DATETIME DEFAULT SYSDATE()
	,MODEL_NUM INT NOT NULL
	,FOREIGN KEY (MODEL_NUM) REFERENCES CAR_INFO(MODEL_NUM)
);

SELECT * FROM SALE_INFO;

SELECT SI.BUYER
	,SI.PHONE
	,SI.BUY_DATE
	,SI.COLOR
	,CI.MODEL_NAME
	,CI.PRICE
FROM SALE_INFO SI
JOIN CAR_INFO CI ON SI.MODEL_NUM = CI.MODEL_NUM
ORDER BY SI.BUY_DATE DESC;
